name: Build

on:
  push:
    branches:
    - master
    tags:
    - '*'

    paths-ignore:
    - ".github/**"
    - "README.md"
    - ".luarc.json"
    - "annotations.lua"

jobs:
  build:
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: BigWigsMods/packager@master
      with:
        args: -p 6124 -a kRNL70Go

